es2016+
List-KR/NamuLink pull request #10
Opened 2022-12-13 16:23 UTC by green1052

2022-12-13 17:02 UTC, piquark6046 requested changes
First of all, it works on my side. [^1]

But, there are issues:
1. Please don't leave a commit message like https://github.com/List-KR/NamuLink/pull/10/commits/9fd474b2f3bcc91fc42077f98574f6f9e6316a35.
Also, reading [this article](https://djkeh.github.io/articles/How-to-write-a-git-commit-message-kor/) is a good idea.

2. I want to adjust and remove many tabs and whitespaces.
Do you agree with me?


By the way, do you have any Apple device? [^2]

[^1]: Mozilla Firefox and Google Chrome with Violentmonkey.
[^2]: It is not required. it is just a question for debugging.

2022-12-13 17:02 UTC, piquark6046 commented on NamuLink.user.js
> -// @grant        unsafeWindow
I remember that AdGuard does not inject when `unsafeWindow` is not granted.
https://github.com/lekakid/ArcaRefresher/pull/9

2022-12-13 17:03 UTC, piquark6046 commented
Of course, you can do my changes request later.

2022-12-13 17:05 UTC, green1052 commented
1. i got it
2. i dont understand
u said 4 tab -> 2 tab?
i dont have apple deivce

2022-12-13 17:06 UTC, green1052 commented on NamuLink.user.js
> -// @grant        unsafeWindow
no, adguard working without unsafeWindow perm

2022-12-13 17:12 UTC, green1052 commented
i prefer 4 tabs

2022-12-13 17:17 UTC, piquark6046 commented
OK. For now, I will use a native feature of Visual Studio Code.

2022-12-13 17:18 UTC, piquark6046 requested changes
@seia-soto Can you test your Safari environment?

2022-12-13 17:20 UTC, piquark6046 commented
https://github.com/List-KR/NamuLink/pull/10#issuecomment-1349130730
To read the result of calling `TypedArray.prototype.slice`.

2022-12-13 17:22 UTC, piquark6046 commented
https://github.com/List-KR/NamuLink/pull/10#issuecomment-1349147651
@green1052 

I don't recommend that.
Please read [this comment](https://github.com/List-KR/NamuLink/issues/7#issuecomment-1324150043).

2022-12-15 05:33 UTC, green1052 commented
> 

1. well i think it is bad for performance

3. https://nomo.asia/429

4. namu.wiki use only Uint8Array
if u want revert i revert that

2022-12-15 11:31 UTC, green1052 commented
so how to do?

2022-12-15 11:39 UTC, piquark6046 commented
First, please revert 3.

2022-12-15 11:42 UTC, green1052 commented
and than?

2022-12-15 11:46 UTC, piquark6046 commented
Finally, please revert no 1 unless. :D

2022-12-15 11:48 UTC, green1052 commented
i think better leave it

2022-12-15 11:51 UTC, piquark6046 commented
Then, do you have any experimental data?

2022-12-15 11:54 UTC, green1052 commented
i tested my code

2022-12-15 11:58 UTC, piquark6046 commented
What did you test? debugging test? Comparing the lead time of each code?

2022-12-15 15:22 UTC, green1052 commented
debugging

2022-12-15 16:28 UTC, piquark6046 commented
I had performed the debugging before i asked.
I want an experimental data.

2022-12-15 17:16 UTC, piquark6046 commented
https://github.com/List-KR/NamuLink/pull/10/commits/a00b20b1caf791310cd0d575adc5dd0191cbd268 ???

2022-12-16 00:46 UTC, Githubmaniak commented
@piquark6046 잘 작동합니다

2022-12-18 19:04 UTC, green1052 commented
need more test?

2022-12-19 08:11 UTC, piquark6046 approved these changes

2022-12-19 08:11 UTC, merged